# Generated by Django 4.1.7 on 2023-05-08 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('dob', models.DateField(default=django.utils.timezone.now, max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('type', models.CharField(default='user', max_length=255)),
            ],
        ),
    ]
